CREATE TABLE IF NOT EXISTS TASK (
    ID VARCHAR(128) NOT NULL,
    TASKNAME VARCHAR(128) NOT NULL,
    LABELNAME VARCHAR(128) NOT NULL,
    TASKPRIORITY VARCHAR(128) NOT NULL,
    TASKSTARTTIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
    );